// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lxocxtgqcxrqrmhduqpx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx4b2N4dGdxY3hycXJtaGR1cXB4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0ODczNjcsImV4cCI6MjA2NDA2MzM2N30.SPhKp62F7ZWnS0OW8bNZb1RJF04ITpP7Joc2V250o9k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);