// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ilusnrvshutxvpgznoba.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlsdXNucnZzaHV0eHZwZ3pub2JhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5Njg3MTEsImV4cCI6MjA2NTU0NDcxMX0.k6A_ePG9esodegYGX4z1dkBOelnSigcsRm8wJhpXRNw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});